services:
  chirp:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017/chirp
    depends_on:
      - mongo

  mongo:
    image: mongo:3.6
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
